  spring:
    application:
      name: salesmgmt

    datasource:
      url: jdbc:mysql://localhost:3306/salesmgmt
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        #      ddl-auto: create-drop
        ddl-auto: update
      show-sql: true

  springdoc:
    api-docs:
      groups:
        enabled: true

    swagger-ui:
      tags-sorter: alpha
      operations-sorter: method
      doc-expansion: none
      path: /api
      tag-sorter: alpha
      display-request-duration: true

    model-and-view-allowed: true


    spring:
      config:
        activate:
          on-profile: test
      datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: test
        password: 1234
      h2:
        console:
          enabled: true

      jpa:
        hibernate:
          ddl-auto: create-drop
        show-sql: true


