name: Test and Coverage Check

on:
  pull_request:
    branches: [ main ]  # PR 대상 브랜치

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Run Tests with Coverage
        run: ./gradlew clean test jacocoTestReport jacocoTestCoverageVerification
